image:
 - Visual Studio 2015

os: unstable

environment:
 QTDIR: 'C:\Qt\5.10.0\mingw53_32'

clone_folder: c:\projects\source

install:
- git submodule update --init --recursive
- cmd: >-
   set PATH=%PATH%;C:\MinGW\bin

build_script:
- cmd: set PATH=%PATH:C:\Program Files\Git\usr\bin;=% 
- cmd: >-
   cd c:\projects\source
   
   mkdir build

   cd build

   cmake c:\projects\source -G "MinGW Makefiles" "-DCMAKE_PREFIX_PATH=%QTDIR%; C:\MinGW\"

   mingw32-make
