language: cpp
sudo: required
dist: trusty

before_install:
 - sudo apt-get install qtbase5-dev
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"

compiler:
 - gcc

script:
 - mkdir build
 - cd build
 - cmake .. && make
 - make test
